<a href="https://colab.research.google.com/github/ganeshkumar1887/Deep-learning/blob/main/practical%20experiments/Implement_basic_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor1 = tf.constant([1, 2, 3, 4])
print(tensor1)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [3]:
tensor2 = tf.zeros((2,3))
print(tensor2)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [4]:
tensor3 = tf.ones((2,3))
print(tensor3)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [5]:
tensor4 = tf.random.uniform((3,3))
print(tensor4)

tf.Tensor(
[[0.4407587  0.8881602  0.12145674]
 [0.43994057 0.07557166 0.6694845 ]
 [0.5114192  0.3570547  0.24838662]], shape=(3, 3), dtype=float32)


In [6]:
print(tensor1.shape)

(4,)


In [7]:
a = tf.constant([2,4,6])
b = tf.constant([1,3,5])

add = tf.add(a,b)
print(add)

tf.Tensor([ 3  7 11], shape=(3,), dtype=int32)


In [8]:
sub = tf.subtract(a,b)
print(sub)

tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [9]:
mul = tf.multiply(a,b)
print(mul)

tf.Tensor([ 2 12 30], shape=(3,), dtype=int32)


In [10]:
div = tf.divide(a,b)
print(div)

tf.Tensor([2.         1.33333333 1.2       ], shape=(3,), dtype=float64)


In [11]:
tensor = tf.constant([[1,2,3,4],[5,6,7,8]])

reshape_tensor = tf.reshape(tensor,(4,2))
print(reshape_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [12]:
tensor = tf.constant([10,20,30])
print(tensor.numpy())

[10 20 30]


In [13]:
tensor = tf.constant([[1,2,3],[4,5,6]])

print(tensor[0][1])   # element
print(tensor[1])      # row

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
